export const P = {
  cel:"#87CEEB", celD:"#4A9CC8",
  brn:"#6B3F2A", brnL:"#A0632A",
  lil:"#C8A2C8", lilD:"#9B72CF",
  trq:"#2EC4B6", trqD:"#1A9E92",
  grn:"#22C55E", red:"#E5534B", gld:"#D4A843",
};

export const TH = {
  light:{ bg:"linear-gradient(135deg,#F5F0FF,#E8F4FD 50%,#F0FFF8)",
    card:"#fff", cardAlt:"#F8F4FE", text:"#1A0A00", sec:"#5A4A5A",
    brd:"#E0D0F0", shd:"0 4px 24px rgba(46,196,182,.12)",
    nav:"rgba(255,255,255,.93)", inp:"#F8F5FF" },
  dark:{ bg:"linear-gradient(135deg,#0A0F1E,#0D1A2A 50%,#0A1A18)",
    card:"#141C30", cardAlt:"#1A2440", text:"#F0ECFF", sec:"#9BBCCC",
    brd:"#1E2A40", shd:"0 4px 24px rgba(46,196,182,.18)",
    nav:"rgba(10,15,30,.95)", inp:"#0E1525" },
};

export const MODULES = [
  { id:1, emoji:"🌱", title:"Fundamentos do Yoga", sub:"Base para uma jornada transformadora",
    level:"Iniciante", color:P.cel, tc:"#1A4060", weeks:3,
    classes:[
      { id:"c1", title:"Saudação ao Sol", min:20, level:"Iniciante",
        desc:"A Surya Namaskar é uma sequência poderosa de 12 posturas que aquece e energiza o corpo inteiro. Praticada há milênios, é perfeita para começar o dia com vitalidade e clareza mental.",
        videoId:"UDTJiVPCPDo",
        videoUrl:"https://www.youtube.com/watch?v=UDTJiVPCPDo",
        thumb:"https://img.youtube.com/vi/UDTJiVPCPDo/maxresdefault.jpg",
        music:"Sons da Natureza ao Amanhecer 🌅",
        musicQ:"yoga+morning+nature+sounds",
        audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
        audioLabel:"🌅 Natureza ao Amanhecer",
        breathTech:"4-4",
        breathDesc:"Inspire contando 4 tempos ao expandir o corpo. Expire contando 4 tempos ao contrair. Respire sempre pelo nariz.",
        breathSteps:[{phase:"Inspire",sec:4,color:"#87CEEB"},{phase:"Expire",sec:4,color:"#2EC4B6"}],
        poses:[
          {name:"Pranamasana",       emoji:"🙏", desc:"Postura de oração. Fique em pé, palmas unidas no peito. Centraliza a mente e ativa a presença."},
          {name:"Hasta Uttanasana",  emoji:"🙌", desc:"Braços estendidos acima, leve arqueamento. Abre o peito e alonga a coluna."},
          {name:"Uttanasana",        emoji:"🏃", desc:"Flexão para frente, mãos tocando o chão. Alonga isquiotibiais e alivia tensão lombar."},
          {name:"Ashwa Sanchalanasana",emoji:"🦵",desc:"Postura do cavaleiro. Perna estendida atrás, quadril baixo. Abre o flexor do quadril."},
          {name:"Phalakasana",       emoji:"💪", desc:"Prancha alta. Corpo reto como tábua. Ativa core, braços e toda a cadeia posterior."},
          {name:"Bhujangasana",      emoji:"🐍", desc:"Cobra. Peito erguido, cotovelos levemente dobrados. Fortalece a lombar e abre o coração."},
          {name:"Adho Mukha Svanasana",emoji:"🐕",desc:"Cachorro olhando para baixo. Corpo em V invertido. Alonga toda a coluna e fortalece braços."},
        ],
        benefits:[
          {text:"Aquece todos os grupos musculares",     icon:"🔥", intensity:90},
          {text:"Aumenta energia e disposição",          icon:"⚡", intensity:85},
          {text:"Melhora flexibilidade geral",           icon:"🤸", intensity:80},
          {text:"Estimula digestão e metabolismo",       icon:"🌿", intensity:70},
          {text:"Acalma e foca a mente",                 icon:"🧘", intensity:75},
        ],
        img:"https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&q=80" },

      { id:"c2", title:"Pranayama e Meditação", min:15, level:"Iniciante",
        desc:"Técnicas ancestrais de controle da respiração que acalmam o sistema nervoso e preparam o corpo e mente para estados profundos de meditação e relaxamento.",
        videoId:"inpok4MKVLM",
        videoUrl:"https://www.youtube.com/watch?v=inpok4MKVLM",
        thumb:"https://img.youtube.com/vi/inpok4MKVLM/maxresdefault.jpg",
        music:"Tibetan Singing Bowls 🔔",
        musicQ:"tibetan+singing+bowls+meditation",
        audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
        audioLabel:"🔔 Tibetan Bowls",
        breathTech:"4-7-8",
        breathDesc:"Técnica 4-7-8 do Dr. Andrew Weil. Inspire 4s, retenha 7s, expire lentamente em 8s. Ativa o sistema nervoso parassimpático.",
        breathSteps:[{phase:"Inspire",sec:4,color:"#87CEEB"},{phase:"Retenha",sec:7,color:"#C8A2C8"},{phase:"Expire",sec:8,color:"#2EC4B6"}],
        poses:[
          {name:"Sukhasana",         emoji:"🧘", desc:"Postura fácil sentada. Pernas cruzadas, coluna ereta. Base estável para qualquer pranayama."},
          {name:"Anulom Vilom",      emoji:"👃", desc:"Respiração alternada pelas narinas. Equilibra os hemisférios cerebrais e acalma profundamente."},
          {name:"Bhramari Pranayama",emoji:"🐝", desc:"Respiração da abelha. Expire zumbindo. Vibração que acalma o sistema nervoso instantaneamente."},
          {name:"Shavasana",         emoji:"💤", desc:"Postura do cadáver. Corpo completamente relaxado no chão. A postura mais importante do yoga."},
        ],
        benefits:[
          {text:"Reduz ansiedade e estresse",            icon:"🕊️", intensity:95},
          {text:"Melhora a qualidade do sono",           icon:"🌙", intensity:88},
          {text:"Aumenta foco e clareza mental",         icon:"🎯", intensity:82},
          {text:"Regula o sistema nervoso",              icon:"⚖️", intensity:90},
          {text:"Diminui pressão arterial",              icon:"❤️", intensity:78},
        ],
        img:"https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500&q=80" },

      { id:"c3", title:"Flexibilidade Suave", min:25, level:"Iniciante",
        desc:"Prática gentil e acessível para ganhar flexibilidade progressivamente, sem dor. Ideal para iniciantes e para quem fica muito tempo sentado.",
        videoId:"v7AYKMP6rOE",
        videoUrl:"https://www.youtube.com/watch?v=v7AYKMP6rOE",
        thumb:"https://img.youtube.com/vi/v7AYKMP6rOE/maxresdefault.jpg",
        music:"Flauta Indiana e Sitar 🪈",
        musicQ:"indian+flute+sitar+yoga",
        audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
        audioLabel:"🪈 Flauta Indiana",
        breathTech:"expire-aprofunda",
        breathDesc:"Expire ao aprofundar cada postura. Nunca force além do conforto — o yoga não é competição. Observe as sensações sem julgamento.",
        breathSteps:[{phase:"Inspire",sec:4,color:"#87CEEB"},{phase:"Expire e afunde",sec:6,color:"#2EC4B6"}],
        poses:[
          {name:"Balasana",          emoji:"🌿", desc:"Postura da criança. Joelhos abertos, testa no chão. Refúgio de descanso entre as posturas."},
          {name:"Marjaryasana",      emoji:"🐱", desc:"Gato-vaca. Alterna arqueamento e arredondamento da coluna. Massageia a coluna vertebral."},
          {name:"Baddha Konasana",   emoji:"🦋", desc:"Postura do sapateiro. Plantas dos pés unidas, joelhos abertos. Abre profundamente o quadril."},
          {name:"Paschimottanasana", emoji:"🧎", desc:"Flexão sentada. Tronco sobre as pernas estendidas. Um dos alongamentos mais completos do yoga."},
        ],
        benefits:[
          {text:"Alivia tensão nas costas e lombar",     icon:"🦴", intensity:92},
          {text:"Aumenta amplitude de movimento",        icon:"🤸", intensity:87},
          {text:"Libera quadris e flexores",             icon:"🦋", intensity:84},
          {text:"Relaxamento profundo do sistema nervoso",icon:"🕊️",intensity:80},
          {text:"Melhora postura e consciência corporal", icon:"⬆️", intensity:76},
        ],
        img:"https://images.unsplash.com/photo-1588286840104-8957b019727f?w=500&q=80" },
    ]},

  { id:2, emoji:"🔥", title:"Força e Equilíbrio", sub:"Construa poder interior e estabilidade",
    level:"Intermediário", color:P.lil, tc:"#3A1060", weeks:4,
    classes:[
      { id:"c4", title:"Sequência dos Guerreiros", min:30, level:"Intermediário",
        desc:"Virabhadrasana I, II e III constroem força muscular, resistência e determinação. Uma das sequências mais transformadoras e completas do yoga dinâmico.",
        videoId:"9kOCY0KNByw",
        videoUrl:"https://www.youtube.com/watch?v=9kOCY0KNByw",
        thumb:"https://img.youtube.com/vi/9kOCY0KNByw/maxresdefault.jpg",
        music:"Eletrônica Ambient Flow ⚡",
        musicQ:"yoga+flow+electronic+ambient",
        audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
        audioLabel:"⚡ Ambient Flow",
        breathTech:"kapalabhati",
        breathDesc:"Kapalabhati — Crânio Brilhante. Expirações curtas e fortes pelo nariz, inspirações passivas. 30 respirações por rodada. Ativa e purifica.",
        breathSteps:[{phase:"Expire forte",sec:1,color:"#FF6B6B"},{phase:"Inspire (passivo)",sec:1,color:"#C8A2C8"}],
        poses:[
          {name:"Virabhadrasana I",  emoji:"⚔️", desc:"Guerreiro I. Pé da frente a 90°, pé de trás a 45°. Braços acima. Força e abertura simultâneas."},
          {name:"Virabhadrasana II", emoji:"🏹", desc:"Guerreiro II. Braços abertos paralelos ao chão, olhar na ponta dos dedos. Força e foco."},
          {name:"Virabhadrasana III",emoji:"🦅", desc:"Guerreiro III. Corpo paralelo ao chão, perna levantada. O máximo de equilíbrio e força."},
          {name:"Utthita Trikonasana",emoji:"△",desc:"Triângulo estendido. Pernas abertas, tronco lateralizado. Abre quadril e alonga lateral."},
        ],
        benefits:[
          {text:"Fortalece quadríceps, glúteos e core",  icon:"💪", intensity:93},
          {text:"Melhora postura e alinhamento",          icon:"⬆️", intensity:88},
          {text:"Aumenta resistência cardiovascular",     icon:"❤️", intensity:82},
          {text:"Desenvolve determinação e foco",         icon:"🎯", intensity:90},
          {text:"Queima calorias e tonifica o corpo",     icon:"🔥", intensity:85},
        ],
        img:"https://images.unsplash.com/photo-1575052814086-f385e2e2ad1b?w=500&q=80" },

      { id:"c5", title:"Equilíbrio e Foco", min:25, level:"Intermediário",
        desc:"Posturas de equilíbrio em um pé desenvolvem concentração profunda, fortalecem tornozelos e criam uma conexão íntima entre corpo e mente.",
        videoId:"X0_tHF9U2wo",
        videoUrl:"https://www.youtube.com/watch?v=X0_tHF9U2wo",
        thumb:"https://img.youtube.com/vi/X0_tHF9U2wo/maxresdefault.jpg",
        music:"Mantras Tibetanos 🕉️",
        musicQ:"om+mani+padme+hum+tibetan",
        audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
        audioLabel:"🕉️ Mantras Tibetanos",
        breathTech:"nadi-shodhana",
        breathDesc:"Nadi Shodhana — Respiração Alternada. Feche a narina direita, inspire pela esquerda (4s). Feche a esquerda, expire pela direita (8s). Repita alternando.",
        breathSteps:[{phase:"Inspire esq",sec:4,color:"#87CEEB"},{phase:"Expire dir",sec:8,color:"#9B72CF"}],
        poses:[
          {name:"Vrksasana",         emoji:"🌳", desc:"Postura da árvore. Um pé no chão, outro na coxa. Braços acima. Equilíbrio e raízes."},
          {name:"Garudasana",        emoji:"🦅", desc:"Postura da águia. Braços e pernas entrelaçados. Força de concentração máxima."},
          {name:"Natarajasana",      emoji:"💃", desc:"Postura do dançarino. Pé seguro atrás, tronco inclinado. Beleza, equilíbrio e abertura."},
          {name:"Ardha Chandrasana", emoji:"🌙", desc:"Meia lua. Pé e mão no chão, corpo aberto lateralmente. Abre quadril e trabalha equilíbrio."},
        ],
        benefits:[
          {text:"Melhora equilíbrio e propriocepção",    icon:"⚖️", intensity:95},
          {text:"Fortalece tornozelos e pés",            icon:"🦶", intensity:88},
          {text:"Aumenta concentração e foco",           icon:"🎯", intensity:92},
          {text:"Reduz distração e ansiedade",           icon:"🕊️", intensity:80},
          {text:"Tonifica pernas e glúteos",             icon:"💪", intensity:75},
        ],
        img:"https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=500&q=80" },
    ]},

  { id:3, emoji:"🪷", title:"Yoga Restaurativo", sub:"Cura profunda e masterclass de posturas",
    level:"Avançado", color:P.trq, tc:"#003830", weeks:6,
    classes:[
      { id:"c6", title:"Yin Yoga Profundo", min:45, level:"Avançado",
        desc:"Posturas mantidas por 3 a 5 minutos, atuando nos tecidos conjuntivos profundos: fáscias, ligamentos e tendões. Uma prática transformadora de cura.",
        videoId:"wPO5HQnOeKQ",
        videoUrl:"https://www.youtube.com/watch?v=wPO5HQnOeKQ",
        thumb:"https://img.youtube.com/vi/wPO5HQnOeKQ/maxresdefault.jpg",
        music:"Ambient Deep Relaxation 🌊",
        musicQ:"yin+yoga+deep+relaxation",
        audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
        audioLabel:"🌊 Deep Relaxation",
        breathTech:"natural",
        breathDesc:"Respiração natural e livre. Não controle — apenas observe. Cada expiração aprofunda o relaxamento. Entregue-se completamente à postura.",
        breathSteps:[{phase:"Observe inspire",sec:4,color:"#87CEEB"},{phase:"Entregue-se expire",sec:6,color:"#2EC4B6"}],
        poses:[
          {name:"Anahatasana",       emoji:"🙏", desc:"Coração derretendo. Peito no chão, braços estendidos. Libera tensão entre as escápulas."},
          {name:"Dragonfly",         emoji:"🦋", desc:"Libélula. Pernas abertas sentado, tronco para frente. Libera adutores e lombar profundos."},
          {name:"Caterpillar",       emoji:"🐛", desc:"Lagarta. Flexão para frente com pernas unidas. Decomprime a coluna vertebral por inteiro."},
          {name:"Reclining Butterfly",emoji:"💎",desc:"Borboleta reclinada. Costas no chão, plantas dos pés unidas. Abre quadril em relaxamento total."},
          {name:"Savasana",          emoji:"💤", desc:"Cadáver. 5 minutos de integração total. O corpo absorve e processa toda a prática."},
        ],
        benefits:[
          {text:"Libera fáscia e tecido conjuntivo profundo",icon:"🔓",intensity:96},
          {text:"Melhora mobilidade articular",            icon:"🤸", intensity:90},
          {text:"Libera emoções armazenadas no corpo",     icon:"💧", intensity:88},
          {text:"Meditação ativa e profunda",              icon:"🧘", intensity:85},
          {text:"Reduz inflamação crónica",                icon:"🌿", intensity:80},
        ],
        img:"https://images.unsplash.com/photo-1518611012118-696072aa579a?w=500&q=80" },

      { id:"c7", title:"Inversões Masterclass", min:40, level:"Avançado",
        desc:"As inversões são as rainha do yoga. Invertem a gravidade, melhoram a circulação cerebral e cultivam coragem. Para praticantes comprometidos.",
        videoId:"fkg_z5oPByQ",
        videoUrl:"https://www.youtube.com/watch?v=fkg_z5oPByQ",
        thumb:"https://img.youtube.com/vi/fkg_z5oPByQ/maxresdefault.jpg",
        music:"Épico — Poder e Superação 🏔️",
        musicQ:"powerful+epic+yoga+music",
        audioUrl:"https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
        audioLabel:"🏔️ Poder e Superação",
        breathTech:"bhastrika",
        breathDesc:"Bhastrika — Fole do Ferreiro. Inspirações E expirações rápidas e fortes. 20 respirações, pausa, repita 3x. APENAS para praticantes avançados.",
        breathSteps:[{phase:"Inspire forte",sec:1,color:"#FF6B6B"},{phase:"Expire forte",sec:1,color:"#D4A843"}],
        poses:[
          {name:"Sirsasana",         emoji:"🙃", desc:"Plantão na cabeça. O rei das posturas. Requer core forte e prática gradual com suporte."},
          {name:"Sarvangasana",      emoji:"🕯️", desc:"Vela. Ombros no chão, pernas ao alto. Estimula tireoide e acalma o sistema nervoso."},
          {name:"Halasana",          emoji:"🌾", desc:"Arado. Pernas atrás da cabeça. Decomprime a coluna cervical e alonga profundamente."},
          {name:"Pincha Mayurasana", emoji:"🦚", desc:"Plantão no antebraço. Equilíbrio total do corpo invertido. Força, foco e coragem máximos."},
        ],
        benefits:[
          {text:"Melhora circulação cerebral e memória",  icon:"🧠", intensity:94},
          {text:"Fortalece core, ombros e pescoço",       icon:"💪", intensity:90},
          {text:"Estimula sistema linfático e imune",     icon:"🛡️", intensity:86},
          {text:"Desenvolve coragem e autoconfiança",     icon:"🦁", intensity:92},
          {text:"Reverte efeitos da gravidade",           icon:"⬆️", intensity:88},
        ],
        img:"https://images.unsplash.com/photo-1510894347713-fc3dc6166086?w=500&q=80" },
    ]},
];

export const COUNTRIES = ["Brasil","Portugal","Angola","Moçambique","Cabo Verde","Timor-Leste","Estados Unidos","Espanha","França","Alemanha","Itália","Argentina","México","Colômbia","Chile","Peru","Japão","China","Índia","Outros"];
export const LEVELS    = ["Iniciante","Intermediário","Avançado","Não sei ainda"];
export const GOALS     = ["Flexibilidade","Redução de estresse","Força muscular","Emagrecimento","Espiritualidade","Saúde geral","Meditação","Reabilitação"];
export const LANGS     = {"pt-BR":"🇧🇷 Português","en-US":"🇺🇸 English","es-ES":"🇪🇸 Español","fr-FR":"🇫🇷 Français","de-DE":"🇩🇪 Deutsch","it-IT":"🇮🇹 Italiano","ja-JP":"🇯🇵 日本語"};
